# - alias: "Turn on Bedroom lights when the sun sets"
#   trigger:
#     platform: sun
#     event: sunset
#     offset: "-01:00:00"
#   # condition:
#   #   condition: state
#   #   entity_id: group.all_devices
#   #   state: 'home'
#   action:
#     service: switch.sonoff_s20_1.turn_on

- alias: 'Turn on Bedroom lights by sunset'
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action: 
    service: switch.turn_on
    entity_id: switch.sonoff_s20_1

- alias: 'Turn off Bedroom lights by night'
  trigger:
    - platform: time
      at: '23:00:00'
  action: 
    service: switch.turn_off
    entity_id: switch.sonoff_s20_1

- alias: 'Flash Sensor 1 Start'
  initial_state: True
  trigger:
    - platform: state
      entity_id: sensor.sensornode1_motion_status
      to: 'Detected'
  action:
    # service: script.turn_on
    # entity_id: script.flash_sensor1_light
    service: light.turn_on
    data:
      entity_id: light.sensornode1_rgb
      # rgb_color: [255,0,0]
      color_name: blue
      flash: short

- alias: 'Flash Sensor 1 Stop'
  trigger:
    platform: state
    entity_id: sensor.sensornode1_motion_status
    to: 'Clear'
  # condition:
  #   condition: state
  #   entity_id: switch.AlmSnd1
  #   to: 'off'
  action:
    service: script.turn_off
    entity_id: script.flash_sensor1_light   

# - alias: 'Turn on Bedroom lights DEMO'
#   trigger:
#     platform: sun
#     event: sunrise
#     # offset: "-02:00:00"
#   action: 
#     service: switch.turn_on
#     entity_id: switch.sonoff_s20_1
