homeassistant:
  # Name of the location where Home Assistant is running
  name: "K.O.T.L" # Keeper Of The Light
  
  # Location required to calculate the time the sun rises and sets
  latitude: !secret location_lat
  longitude: !secret location_long
  
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# CustomUI Auto Install YAML
# customizer:
#   custom_ui: local

# Enables the frontend
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html  
  themes: !include_dir_merge_named themes
  javascript_version: latest
  # themes:
  #   happy:
  #     primary-color: pink
  #   sad:
  #     primary-color: blue
  #   night:
  #     primary-color: darkred

lovelace:
  mode: yaml

# Enables configuration UI
config:
logger:
http:
  # api_password: !secret ha_pass
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: 192.168.1.116:8123

# Discover some devices automatically
# discovery:
# hassio: 
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
  intents:
    ColorLight:
     - Change the mood to [the color] {color}  

lametric:
  client_id: !secret la_client_id
  client_secret: !secret la_client_secret

notify:
  name: LM2216
  platform: lametric
  # icon: a25544
  # lifetime: 7
  # cycles: 1
  # priority: warning

# device_tracker:
#   - platform: owntracks_http
  ##  Moving to Passive/Event Based for OpenWRT - https://github.com/mueslo/openwrt_hass_devicetracker
  # - platform: ubus
  #   host: !secret 3200acm
  #   username: !secret 3200acm_user
  #   password: !secret 3200acm_pass
  #   #dhcp_software: dnsmasq
  #   track_new_devices: yes
# Enables support for tracking state changes over time
history:
recorder:
  purge_keep_days: 7
  db_url: !secret ha_db_url
  exclude:
    domains:
      - automation
    entities:
      - sun.sun # Don't record sun data
      # - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      # - sensor.date
# View all events in a logbook
# logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
# sensor:
#   - platform: yr

# Text to speech
tts:
  - platform: google
    base_url: https://iot.iganesh.com

# Enable HA Cloud
# cloud:

# Google Assistant API
google_assistant:
  project_id: !secret ga_project_id
  # removed from v0.80
  # client_id: !secret ga_client_id
  # access_token: !secret ga_access
  # agent_user_id: !secret ga_agent
  api_key: !secret ga_api
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - script
    - media_player
    # - scene
    # - group

mqtt:
  broker: localhost
  port: 1883
  client_id: hassio
  username: !secret mqtt_broker_user
  password: !secret mqtt_broker_pass

shell_command:
  ##shutdown_apex: "net rpc shutdown -f -t time -C 'message' -U username%password -I ip_address"
  shutdown_apex: !secret cobalt-60-rpc-down
  lock_apex: !secret cobalt-60-rpc-lock
  shell_upgrade_hass: !secret ha_upgrade_sh 
  restart_hass: !secret restart_hass

switch: !include switches.yaml
light: !include lights.yaml
sensor: !include sensors.yaml

# OTHER DEVICES
cast:
  media_player:
    # - host: 192.168.1.139
    - host: 192.168.1.129
# camera:
#   - platform: ffmpeg
#     input: !secret cam1
  # - platform: onvif
  #   host: 192.168.1.200
  #   port: 554
  #   username: !secret cam1_user
  #   password: !secret cam1_pass
  #   name: "Monitor 1"

# INPUT SLIDERS
input_number:
  switch_run_time:
    name: "Switch Run Time"
    initial: 6
    min: 1
    max: 12
    step: 1
input_select:
  xb7_mode:
    name: "Speaker Mode"
    options:
      - XB7 Bluetooth
      - XB7 USB
      - XB7 Aux
    initial: XB7 Bluetooth
    icon: mdi:speaker-multiple
  xb7_lights_mode:
    name: "Lights Mode"
    options:
      - XB7 Rave
      - XB7 Chill
    initial: XB7 Rave
    icon: mdi:car-parking-lights
# HA_VOICE
intent_script:
  ColorLight:
    speech:
      text: Changed the mood to {{ color }}.
    action:
      service: light.turn_on
      data:
        entity_id: light.mood
        color_name: { color }
          # - "{% if color == 'red' %}red{% endif %}"
          # - "{% if color == 'green' %}green{% endif %}"
          # - "{% if color == 'blue' %}blue{% endif %}"
          # - "{% if color == 'purple' %}purple{% endif %}"

#############################################
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
system_health:
custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
weblink:
  entities:
    - name: Release Log
      url: https://github.com/home-assistant/home-assistant/releases/latest
# updater:
#   reporting: false
