title: Home
background: var(--background-image)
resources:
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
  - url: /customcards/github/custom-cards/button-card.js?track=true
    type: module
  - url: /customcards/github/custom-cards/vertical-stack-in-card.js?track=true
    type: module
  - url: /customcards/github/thomasloven/card-tools.js?track=true
    type: js
  - url: /customcards/github/maykar/compact-custom-header.js?track=true
    type: module    
  - url: /local/lovelace/mini-graph-card-bundle.js?track=true
    type: module
  - url: /local/lovelace/mini-media-player-bundle.js?track=true
    type: module
#  - url: /local/mini-media-player-bundle.js?track=true
#    type: js    

views:
  - title: Home
    icon: mdi:home-outline

    # badges:
    cards:
      - type: custom:compact-custom-header
        main_config: true

#### VIEW 1: ______ ####
      
#     ## LIGHTS
      - type: vertical-stack
        cards:
          - type: "custom:button-card"
            name: "Lights"          
            color_type: label-card
            color: var(--primary-background-color)
            style:
              - background-color: var(--primary-background-color)
              - color: var(--primary-text-color)
              - padding-top: 12px
              - padding-bottom: 12px
              - font-weight: bold
              - font-size: 20px
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: light.mood
                name: Mood
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - type: entity-button
                entity: light.lifx_d073d528a0be
                name: Living Room
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info                  
              - type: entity-button
                entity: light.desk_light
                name: Desk
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info                  
              - type: entity-button
                entity: light.room_light
                name: Bedroom
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info                  
#
# #### Home Speakers ####
#           - type: conditional
#             conditions:
#               - entity: media_player.home_speakers
#                 state_not: "off"
#               - entity: media_player.home_speakers
#                 state_not: "unavailable"
#             card:
#               type: media-control
#               entity: media_player.home_speakers
#


#         ## WORKSTATION
          - type: "custom:button-card"
            name: "Workstation"          
            color_type: label-card
            color: var(--primary-background-color)
            style:
              - background-color: var(--primary-background-color)
              - color: var(--primary-text-color)
              - padding-top: 12px
              - padding-bottom: 12px
              - font-weight: bold
              - font-size: 20px
          - type: "custom:vertical-stack-in-card"
            cards:
            - type: picture-glance
              title: "Apex"
              state_image:
                "on": /local/states/workstation.jpg
                "off": /local/states/workstation_off.jpg
              entity: switch.apex
              entities:
                - switch.apex
                - switch.lock_apex
                - light.desk_light
            - type: entities
              entities:
                - entity: switch.sonoff_s31_2
                  name: "Workstation Switch"
                - entity: switch.sonoff_s20_1
                  name: "Workstation Desk"
                - entity: sensor.sonoff_s31_2_sensor_power
                  name: "Power Draw"
                - entity: sensor.sonoff_s31_2_sensor_current
                  name: "Current"
                - entity: sensor.sonoff_s31_2_sensor_today
                  name: "Energy Used Today"

#         ## MEDIA (SPEAKERS, ETC.)
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:        
              - type: "custom:button-card"
                name: "Media"          
                color_type: label-card
                color: var(--primary-background-color)
                style:
                  - background-color: var(--primary-background-color)
                  - color: var(--primary-text-color)
                  - padding-top: 12px
                  - padding-bottom: 12px
                  - font-weight: bold
                  - font-size: 20px  
              - type: picture-glance
                title: "Sony GTK XB-7"
                state_image:
                  "on": /local/states/xb7_on.png?v1
                  "off": /local/states/xb7_off.png?v1
                entity: switch.gtk_xb7
                entities:
                  - entity: switch.gtk_xb7
                    icon: mdi:power
                  - entity: switch.gtk_xb7_vol_up
                    icon: mdi:volume-plus
                  - entity: switch.gtk_xb7_vol_down
                    icon: mdi:volume-minus
                  - entity: switch.gtk_xb7_aux
                    icon: mdi:ethernet-cable
                  - entity: switch.gtk_xb7_lights
                    icon: mdi:track-light
                  - entity: switch.gtk_xb7_extra_bass
                    icon: mdi:speaker-wireless

#### VIEW 2: INTERNET ####

  - title: System
    icon: mdi:console
    cards:
      - type: custom:compact-custom-header
        main_config: true

      ## NANO PI HWINFO
      - type: horizontal-stack
        cards:
        - type: vertical-stack
          cards:
          - type: "custom:button-card"
            name: "NanoPi HWiNFO"          
            color_type: label-card
            color: var(--primary-background-color)
            style:
              - background-color: var(--primary-background-color)
              - color: var(--primary-text-color)
              - padding-top: 12px
              - padding-bottom: 12px
              - font-weight: bold
              - font-size: 20px
          - type: "custom:vertical-stack-in-card"
            cards:
            - type: picture
              # title: "Internet"
              image: /local/states/nanopi_neo_plus2.jpg
            - type: horizontal-stack
              cards:
              - type: entities
                entities:
                  - sensor.nanopi_cpu_usage
                  - sensor.nanopi_cpu_speed
                  - sensor.nanopi_network_usage
                  - sensor.nanopi_memory_usage
                  - sensor.nanopi_disk_usage
                  - sensor.nanopi_temps
                  - sensor.nanopi_uptime
                show_header_toggle: false

      ## HOME ASSISTANT
      - type: horizontal-stack
        cards:
        - type: vertical-stack
          cards:
          - type: "custom:button-card"
            name: "Home Assistant"          
            color_type: label-card
            color: var(--primary-background-color)
            style:
              - background-color: var(--primary-background-color)
              - color: var(--primary-text-color)
              - padding-top: 12px
              - padding-bottom: 12px
              - font-weight: bold
              - font-size: 20px
          - type: "custom:vertical-stack-in-card"
            cards:
            - type: entities
              entities:             
                - sensor.current_version              
                - sensor.ha_uptime
                - sensor.ha_db
                - entity: script.hass_restart
                  name: "Restart Home Assistant"
                  icon: mdi:restart                
              show_header_toggle: false
            - type: conditional
              conditions:
                - entity: sensor.ha_update_found
                  state: "true"
              card:
                type: entities
                entities:
                  # - type: divider
                  - entity: sensor.ha_latest_version
                    icon: mdi:home-alert
                    name: "Latest Version"
                  - entity: script.upgrade_hass
                    icon: mdi:cellphone-arrow-down
          - type: custom:tracker-card
      
      ## NETWORK          
      - type: horizontal-stack
        cards:
        - type: vertical-stack
          cards:
          - type: "custom:button-card"
            name: "Network"          
            color_type: label-card
            color: var(--primary-background-color)
            style:
              - background-color: var(--primary-background-color)
              - color: var(--primary-text-color)
              - padding-top: 12px
              - padding-bottom: 12px
              - font-weight: bold
              - font-size: 20px
          - type: "custom:vertical-stack-in-card"
            cards:
            - type: picture-entity
              title: "Internet"
              state_image:
                "Online": /local/states/3200acm_online.png?v2
                "Offline": /local/states/3200acm_offline.png?v2
              entity: sensor.internet_status
              show_state: false
              show_name: false              
            - type: entities
              entities:             
                - entity: sensor.3200acm_cpu
                  name: "CPU Load"
                  icon: mdi:chip
                - entity: sensor.3200acm_mem
                  name: "Memory Usage"
                  icon: mdi:memory
                - entity: sensor.3200acm_disk
                  name: "Disk Usage"
                  icon: mdi:harddisk
                - entity: sensor.3200acm_uptime
                  name: "Uptime"
                  icon: mdi:av-timer
                - entity: sensor.3200acm_domain1
                  name: "CYFI Cert Expires"
                  icon: mdi:certificate
                - entity: sensor.3200acm_domain2
                  name: "IOT Cert Expires"
                  icon: mdi:certificate
                - entity: sensor.wan_ip
                  name: "WAN IP"
                  icon: mdi:ip-network
                - entity: sensor.3200acm_openwrt_ver
                  name: "OpenWRT Version"
                  icon: mdi:layers
                # - entity: sensor.openwrt_version
                #   name: "OpenWRT Version"
                  # icon: mdi:layers
                - entity: sensor.latest_openwrt_version
                  name: "Latest OpenWRT Version"
                  icon: mdi:information
